---
cluster: phil-dev-east

globals:
  backend:
    type: local

watchers:
- type: logs
  podAnnotation: "admiral.io/logs"
  ignoreContainerAnnotation: "admiral.io/ignore-containers"

- type: events
  filter:
  - NodeNotReady
