---
cluster: phil-dev-east

logs:
  namespace: ""
  backend:
    type: local
  podAnnotation: "admiral.io/logs"
  ignoreContainerAnnotation: "admiral.io/ignore-containers"

events:
  namespace: ""
  backend:
    type: local
  filter:
  - NodeNotReady
