name: Builds

on:
  push:
    branches-ignore:
      - master
      - release
  pull_request:
    branches:
      - master
      - release

jobs:
  build-image:
    name: Run `go build`
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build . -t admiral:temp_build
