name: Build & Push Image on master or tag
on:
  push:
    branches:
      - master
      - 'feature/*'
    tags:
      - 'v.*.*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request_number || github.ref }}
  cancel-in-progress: true

jobs:
  generate_tag:
    uses: phil-inc/public-actions/.github/workflows/generate_tag.yaml@master
  build_push:
    uses: phil-inc/public-actions/.github/workflows/build_push.yaml@master
    needs: generate_tag
    if: needs.generate_tag.outputs.tag != ''
    secrets: inherit
    with:
      name: admiral
      tag: ${{ needs.generate_tag.outputs.tag }}
      push: ${{ github.event_name != 'pull_request' }}
      notify: true

  gitops_tagger:
    runs-on: ubuntu-22.04
    needs: generate_tag
    steps:
      - name: Sign payload
        env:
          GITOPS_TAGGER_SECRET_KEY: ${{ secrets.GITOPS_TAGGER_SECRET_KEY }}
        run: | 
          PAYLOAD=$(echo '{"repository":"git@github.com:phil-inc/phil-cicd.git","tag":"${{ needs.generate_tag.outputs.tag }}","application":"admiral"}')
          SIGNED_PAYLOAD=$(echo ${PAYLOAD} | openssl sha256 -hmac '${GITOPS_TAGGER_SECRET_KEY}')
          curl -v https://gitops-tagger.dev.phil.us/webhook \
            -H 'Content-Type: application/json' \
            -H 'x-phil-signature: sha256=${SIGNED_PAYLOAD}' \
            -X POST --data ${PAYLOAD}
    
