name: Build & Push Image on master or tag
on:
  push:
    branches:
      - master
      - 'feature/*'
    tags:
      - 'v*.*.*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request_number || github.ref }}
  cancel-in-progress: true

jobs:
  build_push:
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
    - name: generate-tag
      uses: phil-inc/public-actions/.github/actions/generate-tag@master

    - name: build-push
      if: ${{ env.tag }} != ''
      uses: phil-inc/public-actions/.github/actions/build-push@master
      with:
        name: admiral
        tag: ${{ env.tag }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: "us-east-1"
        push: ${{ github.event_name != 'pull_request' }}
        notify: ${{ github.event_name != 'pull_request' }}
        google-chat-webhook: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
        docker-username: ${{ secrets.docker_username }}
        docker-password: ${{ secrets.docker_password }}

    - name: gitops-tagger
      uses: phil-inc/public-actions/.github/actions/gitops-tagger@master
      if: ${{ github.event_name != 'pull_request' }}
      with:
        application: admiral
        gitops_tagger_secret_key: ${{ secrets.GITOPS_TAGGER_SECRET_KEY }}
        tag: ${{ env.tag }}

    - name: archive-repo
      uses: phil-inc/public-actions/.github/actions/archive-repo@master
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        assume-role: ${{ secrets.ARCHIVE_CODE_REPOSITORIES_ROLE }}
