name: Lint, test, code cov, & build image on master, feature, or tag
on: 
  push:
    branches:
      - master
    tags:
      - 'v*'
jobs:
  generate_tag:
    uses: phil-inc/public-actions/.github/workflows/generate_tag.yaml@master
    needs: test-repo
  build_push:
    uses: phil-inc/public-actions/.github/workflows/build_push.yaml@master
    needs: generate_tag
    if: needs.generate_tag.outputs.tag != ''
    secrets: inherit
    with:
      name: admiral
      tag: ${{ needs.generate_tag.outputs.tag }}
      push: true
