name: Build & Push Image on master or tag
on: 
  push:
    branches:
      - master
    tags:
      - 'v*'
jobs:
  generate_tag:
    uses: phil-inc/public-actions/.github/workflows/generate_tag.yaml@master
  build_push:
    uses: phil-inc/public-actions/.github/workflows/build_push.yaml@master
    needs: generate_tag
    if: needs.generate_tag.outputs.tag != ''
    secrets: inherit
    with:
      name: admiral
      tag: ${{ needs.generate_tag.outputs.tag }}
      push: true
      notify: true
  build_push_ecr:
    uses: phil-inc/public-actions/.github/workflows/build_push_ecr.yaml@master
    needs: generate_tag
    if: needs.generate_tag.outputs.tag != ''
    secrets: inherit
    with:
      name: admiral
      tag: ${{ needs.generate_tag.outputs.tag }}
      push: true
      notify: false
