name: Builds

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-repo:
    name: Lint & format code
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: go fmt
        run: if [ "$(make fmt_list | wc -l)" -gt 1 ]; then exit 1; fi
  build-image:
    name: Run `go build`
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: docker build . -t admiral:temp_build
