name: Build & Push Image on master or tag
on:
  push:
    branches:
      - master
    pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request_number || github.ref }}
  cancel-in-progress: true

jobs:
  generate-tag:
    uses: phil-inc/public-actions/.github/workflows/generate_tag.yaml@master
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: generate-tag
    steps:
      - uses: actions/checkout@v3
      - name: Docker Build
        run: docker build . -t philinc/admiral:${{ needs.generate-tag.outputs.tag }}
      - name: Docker Push
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          docker login -u ${{ secrets.docker_username }} -p ${{ secrets.docker_password }}
          docker push philinc/admiral:${{ needs.generate-tag.outputs.tag }}
