name: Build & Push Image on master or tag
on:
  push:
    branches:
      - master
      - 'feature/*'
    tags:
      - 'v.*.*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request_number || github.ref }}
  cancel-in-progress: true

jobs:
  generate_tag:
    uses: phil-inc/public-actions/.github/workflows/generate_tag.yaml@master
  build_push:
    uses: phil-inc/public-actions/.github/workflows/build_push.yaml@master
    needs: generate_tag
    if: needs.generate_tag.outputs.tag != ''
    secrets: inherit
    with:
      name: admiral
      tag: ${{ needs.generate_tag.outputs.tag }}
      push: ${{ github.event_name != 'pull_request' }}
      notify: true

  gitops_tagger:
    runs-on: ubuntu-22.04
    needs: [generate_tag, build_push]
    if: ${{ github.event_name != 'pull_request' }}
    steps:
      - uses: phil-inc/public-actions/.github/actions/gitops-tagger@master
        with:
          application: admiral
          gitops_tagger_secret_key: ${{ secrets.GITOPS_TAGGER_SECRET_KEY }}
          tag: ${{ needs.generate_tag.outputs.tag }}
