name: Tags

on:
  push:
    tags:
      - 'v*'

jobs:
  release-image:
    name: Build & Release Container Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build
        run: docker build . -t philinc/admiral:${{ env.RELEASE_VERSION }}
      - name: Login
        run: docker login -u ${{ secrets.docker_username }} -p ${{ secrets.docker_password }}
      - name: Push
        run: docker push philinc/admiral:${{ env.RELEASE_VERSION }}
